apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform-deployment
spec:
  selector:
    matchLabels:
      app: platform
  replicas: 2
  template:
    metadata:
      labels:
        app: platform
    spec:
      containers:
      - name: platform
        image: CONTAINER_IMAGE
        ports:
        - containerPort: 8080
